public enum EObjectType
{
    HandAxe, BattleAxe, Axe, Dagger, // clump up so the line numbers match the enums
    Shortsword,
    Longsword,
    Broadsword,
    Cudgel,
    LightMace,
    Mace,
    ShinySword,
    JeweledAxe,
    BlackSword,
    JeweledSword,
    JeweledMace,
    Fist,
    SlingStone,
    CrossbowBolt,
    Arrow,
    Stone,
    Fireball,
    LightningBolt,
    Acid,
    MagicMissile,
    Sling,
    Bow,
    Crossbow,
    Knife, // knife thrown by mages. not part of original game.
    Unk28,
    Unk29,
    Unk30,
    JeweledBow,
    LeatherVest,
    MailShirt,
    Breastplate,
    LeatherLeggings,
    MailLeggings,
    PlateLeggings,
    LeatherGloves,
    ChainGauntlets,
    PlateGauntlets,
    LeatherBoots,
    ChainBoots,
    PlateBoots,
    LeatherCap,
    ChainCowl,
    Helmet,
    DragonskinBoots,
    CrownA,
    CrownB,
    CrownC,
    Unk51,
    Unk52,
    Unk53,
    IronRing,
    ShinyShield,
    GoldRing,
    SilverRing,
    RedRing,
    TowerShield,
    WoodenShield,
    SmallShield,
    Buckler,
    JeweledShield,
    Rotworm,
    FleshSlug,
    CaveBat,
    GiantRatBrown,
    GiantSpider,
    AcidSlug,
    GoblinA,
    GoblinB,
    GiantRatGrey,
    VampireBat,
    Skeleton,
    Imp,
    GoblinC,
    GoblinD,
    GoblinE,
    TwilightZoneA,
    GoblinF,
    Mongbat,
    Bloodworm,
    WolfSpider,
    MountainmanA,
    GreenLizardman,
    MountainmanB,
    Lurker,
    RedLizardman,
    GreyLizardman,
    Outcast,
    Headless,
    DreadSpider,
    FighterA,
    FighterB,
    FighterC,
    Troll,
    GhostA,
    FighterD,
    GhoulA,
    GhostB,
    GhostC,
    Gazer,
    MageA,
    FighterE,
    DarkGhoul,
    MageB,
    Sorceress,
    MageD,
    MageE,
    GhoulB,
    FeralTroll,
    GreatTroll,
    DireGhost,
    EarthGolem,
    MageF,
    DeepLurker,
    ShadowBeast,
    Reaper,
    StoneGolem,
    FireElemental,
    MetalGolem,
    Wisp,
    Tyball,
    SlasherOfVeils,
    TwilightZoneB,
    TwilightZoneC,
    Avatar,
    Sack,
    OpenSack,
    Pack,
    OpenPack,
    Box,
    OpenBox,
    Pouch,
    OpenPouch,
    MapCase,
    OpenMapCase,
    GoldCoffer,
    OpenGoldCoffer,
    Urn,
    Quiver,
    Bowl,
    RuneBag,
    Lantern,
    Torch,
    Candle,
    Taper,
    LitLantern,
    LitTorch,
    LitCandle,
    LitTaper,
    WandA,
    WandB,
    WandC,
    WandD,
    BrokenWandA,
    BrokenWandB,
    BrokenWandC,
    BrokenWandD,
    Coin,
    GoldCoin,
    Ruby,
    RedGem,
    SmallBlueGem,
    LargeBlueGem,
    Sapphire,
    Emerald,
    Amulet,
    Goblet,
    Sceptre,
    GoldChain,
    GoldPlate,
    AnkhPendant,
    ShinyCup,
    LargeGoldNugget,
    PieceOfMeat,
    LoafOfBreadA,
    PieceOfCheese,
    Apple,
    EarOfCorn,
    LoafOfBreadB,
    Fish,
    Popcorn,
    Mushroom,
    Toadstool,
    BottleOfAle,
    RedPotion,
    GreenPotion,
    BottleOfWater,
    FlaskOfPort,
    BottleOfWine,
    Plant,
    Grass,
    SkullA,
    SkullB,
    BoneA,
    BoneB,
    PileOfBonesA,
    Vines,
    BrokenAxe,
    BrokenSword,
    BrokenMace,
    BrokenShield,
    PieceOfWoodA,
    PieceOfWoodB,
    PlantB,
    PlantC,
    PileOfDebrisA,
    PileOfDebrisB,
    PileOfDebrisC,
    Stalactite,
    PlantD,
    PileOfDebrisD,
    PileOfDebrisE,
    Anvil,
    Pole,
    DeadRotworm,
    Rubble,
    PileOfWoodChips,
    PileOfBonesB,
    BloodStainA,
    BloodStainB,
    BloodStainC,
    Runestone,
    KeyOfTruth,
    KeyOfLove,
    KeyOfCourage,
    TwoPartKeyA,
    TwoPartKeyB,
    TwoPartKeyC,
    KeyOfInfinity,
    RunestoneAn,
    RunestoneBet,
    RunestoneCorp,
    RunestoneDes,
    RunestoneEx,
    RunestoneFlam,
    RunestoneGrav,
    RunestoneHur,
    RunestoneIn,
    RunestoneJux,
    RunestoneKal,
    RunestoneLor,
    RunestoneMani,
    RunestoneNox,
    RunestoneOrt,
    RunestonePor,
    RunestoneQuas,
    RunestoneRel,
    RunestoneSanct,
    RunestoneTym,
    RunestoneUus,
    RunestoneVas,
    RunestoneWis,
    RunestoneYlem,
    KeyA,
    Lockpick,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    Lock,
    PictureOfTom,
    CrystalSplinter,
    OrbRock,
    GemCutterOfCoulnes,
    ExplodingBook,
    BlockOfBurningIncense,
    BlockOfIncense,
    Orb,
    BrokenBlade,
    BrokenHilt,
    Figurine,
    RotwormStew,
    StrongThread,
    DragonScales,
    ResilientSphere,
    Standard,
    Spell,
    Bedroll,
    SilverSeed,
    Mandolin,
    Flute,
    Leeches,
    Moonstone,
    Spike,
    RockHammer,
    GlowingRock,
    Campfire,
    FishingPole,
    Medallion,
    OilFlask,
    Fountain,
    Cauldron,
    BookA,
    BookB,
    BookC,
    BookD,
    BookE,
    BookF,
    BookOfHonesty,
    BookH,
    ScrollA,
    ScrollB,
    ScrollC,
    Map,
    ScrollD,
    ScrollE,
    ScrollF,
    ScrollG,
    DoorA,
    DoorB,
    DoorC,
    DoorD,
    DoorE,
    DoorF,
    Portcullis,
    SecretDoor,
    OpenDoorA,
    OpenDoorB,
    OpenDoorC,
    OpenDoorD,
    OpenDoorE,
    OpenDoorF,
    OpenPortcullis,
    OpenSecretDoor,
    Bench,
    ArrowB,
    CrossbowBoltB,
    LargeBoulder,
    MediumBoulder,
    Boulder,
    SmallBoulder,
    Shrine,
    Table,
    Beam,
    Moongate,
    Barrel,
    Chair,
    Chest,
    Nightstand,
    LotusEspritTurbo,
    Pillar,
    RotaryLever,
    Switch,
    Unk355,
    Bridge,
    Gravestone,
    Writing,
    
    
    Shelf = 361, // added
    Arial,
    
    
    ForceField = 365,
    Decal,
    DecalWithCollision,

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    DamageTrap = 384,
    TeleportTrap,
    ArrowTrap,
    DoTrap,
    PitTrap, // this is something other than pit - see the three buttons next to the door on level 3
    ChangeTerrainTrap,
    SpellTrap,
    CreateObjectTrap,
    DoorTrap,
    WardTrap,
    TellTrap,
    DeleteObjectTrap,
    InventoryTrap,
    SetVariableTrap,
    CheckVariableTrap,
    CombinationTrap,
    TextStringTrap,
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    MoveTrigger = 416,
    PickupTrigger,
    UseTrigger,
    LookTrigger,
    StepOnTrigger,
    OpenTrigger,
    UnlockTrigger,
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    Blood = 448,
    MistCloud,
    ExplosionA,
    ExplosionB,
    ExplosionC,
    SplashA,
    SplashB,
    SpellEffect,
    Smoke,
    FountainWater,
    SilverTree,
    Damage,
}
